### ISSUE TITLE
Autocomplete shows strange query parameter for /me/messages endpoint

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-explorer-v4#2740]
**Describe the bug**
Not sure whether it is a bug or not, but the autocomplete for `/me/messages` shows a query parameter `includeHiddenMessages`.

![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/7744844/1273e1fd-3955-4f93-8213-b31d21f52792)

I didn't find the `includeHiddenMessages` parameter in the official Graph API doc, so I'm not sure why the autocomplete displays it. Not even sure how to set up the value (bool/enum,etc.) and what's the expected result.

**To Reproduce**
1. type /me/messages/
2. autocomplete will display `includeHiddenMessages` parameter

**Expected behavior**
If the `includeHiddenMessages` parameter doesn't have any influence on the result, it should not be displayed

**Screenshots**
![image](https://github.com/microsoftgraph/microsoft-graph-explorer-v4/assets/7744844/1273e1fd-3955-4f93-8213-b31d21f52792)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [ALL]
 - Version []

**Smartphone (please complete the following information):**

**Additional context**

**Comment by irvinesunday** [comment]
The includeHiddenMessages is an optional custom query option that can be passed as a query parameter. See the API definition for it here in CSDL:

```XML
<NavigationProperty Name="messages" Type="Collection(graph.message)" ContainsTarget="true">
  <Annotation Term="Org.OData.Capabilities.V1.NavigationRestrictions">
    <Record>
      <PropertyValue Property="RestrictedProperties">
        <Collection>
          <Record>
            <PropertyValue Property="ReadRestrictions">
              <Record>
                <PropertyValue Property="CustomQueryOptions">
                  <Collection>
                    <Record>
                      <PropertyValue Property="Name" String="includeHiddenMessages" />
                      <PropertyValue Property="Description" String="Include Hidden Messages" />
                      <PropertyValue Property="Required" Bool="false" />
                    </Record>
                  </Collection>
                </PropertyValue>
              </Record>
            </PropertyValue>
          </Record>
        </Collection>
      </PropertyValue>
    </Record>
  </Annotation>
  <Annotation Term="Org.OData.Core.V1.Description" String="The messages in a mailbox or folder. Read-only. Nullable." />
</NavigationProperty>
```

And in OpenAPI:

```YAML
/me/messages:
  description: Provides operations to manage the messages property of the microsoft.graph.user entity.
  get:
    tags:
      - me.message
    summary: Get messages from me
    description: The messages in a mailbox or folder. Read-only. Nullable.
    externalDocs:
      description: Find more info here
      url: https://docs.microsoft.com/graph/api/user-list-messages?view=graph-rest-1.0
    operationId: me.ListMessages
    parameters:
      - name: includeHiddenMessages
        in: query
        description: Include Hidden Messages
        schema:
          type: string

```

@ElinorW it might be a good feature idea to add descriptions to the query parameters in the drop down options.
