### ISSUE TITLE
Add credscan to Azure pipelines

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/microsoft-graph-explorer-v4#592]
**Is your feature request related to a problem? Please describe.**

All repos should run credscan task to make sure we are not checking in credentials.
https://github.com/microsoftgraph/microsoft-graph-explorer-v4/blob/dev/azure-pipelines.yml

**Describe the solution you'd like**

```yaml
- task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
  displayName: 'Run CredScan'
  inputs:
    debugMode: false
```

We will likely have to add a suppression file since we have samples that have password in them.

**Additional context**
This addresses [OXO4007424](https://office.visualstudio.com/OXOSec/_workitems/edit/4007424).
 
[AB#7510](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7510)
